### ISSUE TITLE
Unable to connect to remote ollama.

### ISSUE THREAD

**Issue by microsuperman** [bahelit/ctrl_plus_revise#1]
running the binary you provided with the command.

OLLAMA_HOST=http://192.168.50.60:11434; ./ctrl_plus_revise-linux-amd64

I get.

2024/08/15 11:53:20 INFO Using xclip
2024/08/15 11:53:20 INFO Starting Ctr+Revise gui Service... Version=0.0.7 Compiler=go1.22.5
2024/08/15 11:53:20 WARN Failed to load icon error="open /app/share/icons/hicolor/256x256/apps/com.bahelit.ctrl_plus_revise.png: no such file or directory"
2024/08/15 11:53:20 WARN Failed to load icon error="open images/icon.png: no such file or directory"
WARNING: failed to read int from file: open /sys/class/drm/card0/device/numa_node: no such file or directory
WARNING: error parsing the pci address "simple-framebuffer.0"
2024/08/15 11:53:20 WARN Failed to get GPU info
2024/08/15 11:53:20 INFO GPU Probe Driver=nvidia Product="TU116 [GeForce GTX 1660 SUPER]"
2024/08/15 11:53:20 INFO Detected Nvidia GPU Product="TU116 [GeForce GTX 1660 SUPER]"
2024/08/15 11:53:20 INFO System Memory Total=32.00GB Available=31.24GB
2024/08/15 11:53:20 INFO Registered hotkeys
2024/08/15 11:53:20 INFO Ctrl+Revise is ready to help you!
2024/08/15 11:53:20 ERROR Ollama doesn't appear to be running error="Head \"http://127.0.0.1:11434/\": dial tcp 127.0.0.1:11434: connect: connection refused"
2024/08/15 11:53:20 ERROR Ollama heartbeat timed out
2024/08/15 11:53:20 INFO Starting Ollama
2024/08/15 11:53:20 ERROR Can't find Ollama error="exec: \"ollama\": executable file not found in $PATH"

Other front ends on my pc are able to connect to my ollama server.

**Comment by bahelit** [comment]
Thanks for reporting the issue.

After testing can see the issue is that the environment variable needs to be exported.

Adding "export" to the command will resolve your issue.
`export OLLAMA_HOST=http://192.168.50.60:11434; ./ctrl_plus_revise-linux-amd64`

Have updated the README.md with this info, thanks!

Please let me know if you're still experiencing issues.
