### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MAY4VFX** [bahelit/ctrl_plus_revise#2]
does not start on macbook pro m2 sequoia 15.0

![2024-09-20_14-18](https://github.com/user-attachments/assets/7cfef86e-8e90-4958-ae9b-8838368509e4)

**Comment by bahelit** [comment]
Thanks for reporting.

Is this error occurring when opening the dmg file for installing, or is it happening attempting to launch the application?

**Comment by MAY4VFX** [comment]
this happens after installation, when run app, I found a way to fix it with the command: sudo xattr -r -c "path to app"
